[package]
name = "dlss_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "f781a6b6caeeaa76817e2811544939662b5bdf56" }
wgpu-hal = { git = "https://github.com/gfx-rs/wgpu", rev = "f781a6b6caeeaa76817e2811544939662b5bdf56" }
ash = "0.38"
glam = "0.29"
uuid = "1"
bitflags = "2"
thiserror = "1"

[build-dependencies]
bindgen = "0.71"
