[package]
name = "dlss_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.15"
wgpu-core = "0.15"
ash = "0.37"
thiserror = "1.0"

[build-dependencies]
bindgen = { version = "0.64", features = ["experimental"] }
