[package]
name = "dlss_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/jms55/wgpu" }
wgpu-core = { git = "https://github.com/jms55/wgpu" }
wgpu-hal = { git = "https://github.com/jms55/wgpu" }
ash = "0.37"
glam = "0.23"
uuid = "1.3"
bitflags = "2.0"
thiserror = "1.0"

[build-dependencies]
bindgen = { version = "0.64", features = ["experimental"] }
